import type { RouteRecordRaw } from 'vue-router'

const publicRoutes = [
  {
    path: '/',
    name: 'home',
    component: () => import('@/views/Home.vue'),
    meta: { access: 'public' },
  },
  {
    path: '/auditor',
    name: 'auditor',
    component: () => import('@/views/dashboards/auditor/AuditorDashboard.vue'),
    meta: { access: 'auditor', requiresAuth: true },
  },
  {
    path: '/auditor/properties',
    name: 'auditor-properties',
    component: () => import('@/views/dashboards/auditor/PropertyListings.vue'),
    meta: { access: 'auditor', requiresAuth: true },
  },
  {
    path: '/auditor/audit-cases',
    name: 'auditor-audit-cases',
    component: () => import('@/views/dashboards/auditor/AuditCases.vue'),
    meta: { access: 'auditor', requiresAuth: true },
  },
  {
    path: '/auditor/cases',
    name: 'auditor-cases',
    component: () => import('@/views/dashboards/auditor/Cases.vue'),
    meta: { access: 'auditor', requiresAuth: true },
  },
  {
    path: '/auditor/flagged-cases',
    name: 'auditor-flagged-cases',
    component: () => import('@/views/dashboards/auditor/FlaggedCases.vue'),
    meta: { access: 'auditor', requiresAuth: true },
  },
  {
    path: '/auditor/successful-filings',
    name: 'auditor-successful-filings',
    component: () => import('@/views/dashboards/auditor/SuccessfulFilings.vue'),
    meta: { access: 'auditor', requiresAuth: true },
  },
  {
    path: '/auditor/land-registry',
    name: 'auditor-land-registry',
    component: () => import('@/views/dashboards/auditor/LandRegistry.vue'),
    meta: { access: 'auditor', requiresAuth: true },
  },
  {
    path: '/auditor/settings',
    name: 'auditor-settings',
    component: () => import('@/views/dashboards/auditor/Settings.vue'),
    meta: { access: 'auditor', requiresAuth: true },
  },
  {
    path: '/taxpayer',
    name: 'taxpayer',
    component: () => import('@/views/dashboards/developer/DeveloperDashboard.vue'),
    meta: { access: 'taxpayer', requiresAuth: true },
  },
  {
    path: '/taxpayer/properties',
    name: 'taxpayer-properties',
    component: () => import('@/views/dashboards/developer/Properties.vue'),
    meta: { access: 'taxpayer', requiresAuth: true },
  },
  {
    path: '/taxpayer/notices',
    name: 'taxpayer-notices',
    component: () => import('@/views/dashboards/developer/Notices.vue'),
    meta: { access: 'taxpayer', requiresAuth: true },
  },
  {
    path: '/taxpayer/payments',
    redirect: '/taxpayer/properties',
    meta: { access: 'taxpayer', requiresAuth: true },
  },
  {
    path: '/taxpayer/settings',
    name: 'taxpayer-settings',
    component: () => import('@/views/dashboards/developer/Settings.vue'),
    meta: { access: 'taxpayer', requiresAuth: true },
  },
  // {
  //   path: '/compliance',
  //   name: 'compliance',
  //   component: () => import('@/views/dashboards/compliance/ComplianceDashboard.vue'),
  //   meta: { access: 'compliance', requiresAuth: true },
  // },
  // {
  //   path: '/compliance/properties',
  //   name: 'compliance-properties',
  //   component: () => import('@/views/dashboards/compliance/Properties.vue'),
  //   meta: { access: 'compliance', requiresAuth: true },
  // },
  // {
  //   path: '/compliance/flagged',
  //   name: 'compliance-flagged',
  //   component: () => import('@/views/dashboards/compliance/FlaggedProperties.vue'),
  //   meta: { access: 'compliance', requiresAuth: true },
  // },
  // {
  //   path: '/compliance/land-registry',
  //   name: 'compliance-land-registry',
  //   component: () => import('@/views/dashboards/compliance/LandRegistry.vue'),
  //   meta: { access: 'compliance', requiresAuth: true },
  // },
  // {
  //   path: '/compliance/notes',
  //   name: 'compliance-notes',
  //   component: () => import('@/views/dashboards/compliance/ComplianceNotes.vue'),
  //   meta: { access: 'compliance', requiresAuth: true },
  // },
  // {
  //   path: '/compliance/settings',
  //   name: 'compliance-settings',
  //   component: () => import('@/views/dashboards/compliance/Settings.vue'),
  //   meta: { access: 'compliance', requiresAuth: true },
  // },
  {
    path: '/admin',
    name: 'admin',
    component: () => import('@/views/dashboards/admin/AdminDashboard.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
  {
    path: '/admin/rules',
    name: 'admin-rules',
    component: () => import('@/views/dashboards/admin/Rules.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
  {
    path: '/admin/properties',
    name: 'admin-properties',
    component: () => import('@/views/dashboards/admin/Properties.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
  {
    path: '/admin/taxpayers',
    name: 'admin-taxpayers',
    component: () => import('@/views/dashboards/admin/Taxpayers.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
  {
    path: '/admin/revenue',
    name: 'admin-revenue',
    component: () => import('@/views/dashboards/admin/Revenue.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
  {
    path: '/admin/cases',
    name: 'admin-cases',
    component: () => import('@/views/dashboards/admin/Cases.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
  {
    path: '/admin/audits',
    name: 'admin-audits',
    component: () => import('@/views/dashboards/admin/Audits.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
  {
    path: '/admin/compliance',
    name: 'admin-compliance',
    component: () => import('@/views/dashboards/admin/Compliance.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
  {
    path: '/admin/reports',
    name: 'admin-reports',
    component: () => import('@/views/dashboards/admin/Reports.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
  {
    path: '/admin/users',
    name: 'admin-users',
    component: () => import('@/views/dashboards/admin/Users.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
  {
    path: '/admin/notifications',
    name: 'admin-notifications',
    component: () => import('@/views/dashboards/admin/Notifications.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
  {
    path: '/admin/settings',
    name: 'admin-settings',
    component: () => import('@/views/dashboards/admin/AdminSettings.vue'),
    meta: { access: 'admin', requiresAuth: true },
  },
] as const satisfies readonly RouteRecordRaw[]

export default publicRoutes
